### ISSUE TITLE
Is survey start_day fixed?

### ISSUE THREAD

**Issue by Blevy2** [pdolder/MixFishSim#3]
Hi @pdolder ,

I may have found another small bug in the package. I believe that regardless of what is set for the scientific survey start_day, it appears that init_survey fixes the start_day as 92 on line 59 when station_days are created.

Ben Levy

**Comment by pdolder** [comment]
Thanks Ben, yes I can see that is fixed irrespective of input. I'll look at best way of changing it.

**Comment by Blevy2** [comment]
Hi Paul,

I think you can just change the value of 92 to start_day.

Ben

**Comment by pdolder** [comment]
Hi Ben,

On the face of it I think that's right, I'm just wanting to make sure it doesn't cause an error somewhere else with different values. There are not fishing events on every day, if I recall, so want to avoid being able to set a day that doesn't work and causing a crash or bug later in the code.

Maybe this isn't a problem as I can see I put a stop error in there, but to be sure....

Paul

**Comment by pdolder** [comment]
Apologies for the delay, this should now be fixed.
