### ISSUE TITLE
Idea to improve speed

### ISSUE THREAD

**Issue by Blevy2** [pdolder/MixFishSim#9]
Hi Paul,

I had an idea to speed things up that I am struggling to implement, possibly because it involves the Rcpp code. 

As I have been analyzing some simulations I realized that many of the cells in the simulations have zero values. I believe this is because many of the habitat cells (hab[["hab"]]) are zero, which results in no movement to those cells at any point during the simulation. My idea to improve speed is to ignore these cells when going through movement. I am trying to achieve this by doing two things:

1) Avoid distributing zero values during movement. To do this, in move_population inside of movement.cpp, CellPop is defined as the population in a given cell. I create an if statement that only distributes the CellPop value to all other cells in the domain if CellPop >0.

2) In move_population we then only want to distribute a nonzero CellPop value to all **nonzero** cells in the domain. Thus we want to loop through only the nonzero cells in moveProp. To do this I pass in a vector of row and column values that are nonzero in hab[["hab"]][[i]] and loop through those values rather than looping through all row and columns.

Combined this should result in only distributing cells with nonzero population values to cells with nonzero habitat values. Judging by the number of zeros I have in my habitat this should significantly speed things up. 

I have some code written that I think should do this but I believe I am struggling with recompiling the rcpp code. Are you able to help with this? It could be a nice update to the package. 

best,

Ben

**Comment by pdolder** [comment]
Hi Ben,

Apologies for the slow reply...happy to have a look at it, what's the error message?   If you email the Cpp function and I can try compiling.

My initial thought is that this wouldn't speed things up too much because the C++ code is so quick anyway, but I'm not sure on that point - especially if you're using a very large domain.

Paul

**Comment by Blevy2** [comment]
Hi Paul,

No problem at all on the delay. Thanks for being willing to give this a try. Although movement is pretty quick considering how many operations are taking place, profiling shows that movement does account for much of the processing time I am currently experiencing (fishing has been removed). I am on a 100x100 grid in my model so that there are 10,000 cells, with about half of them being assigned a habitat value of zero. Taking the population on each cell and distributing it to every cell in the domain is 10000*10000 = 100 million operations per species per movement event. When I really stop and think about how many operations are taking place during movement it is really amazing how quick it currently is. At the same time, if we only take nonzero cells and distribute them to nonzero it could be more like 5000*5000 = 25 million operations. 

I will email the cpp function now with a description of the few differences.

Thanks for your help!

Ben
